# LambDynamicLights configuration.
# The dynamic lights mode
mode = "fancy"

# Light sources settings.
[light_sources]
	# Enables water-sensitive light sources check. This means that water-sensitive items will not light up when submerged in water.
	water_sensitive_check = true
	# Enable block entities light source.
	block_entities = true
	# Enable entities light source.
	entities = true
	# TNT lighting mode. May be off, simple or fancy.
	tnt = "off"
	# Creeper lighting mode. May be off, simple or fancy.
	creeper = "simple"

	[light_sources.settings]

		[light_sources.settings.entities]

			[light_sources.settings.entities.minecraft]
				axolotl = true
				bee = true
				arrow = true
				cow = true
				magma_cube = true
				pig = true
				skeleton = true
				bat = true
				husk = true
				experience_bottle = true
				rabbit = true
				firework_rocket = true
				armor_stand = true
				drowned = true
				experience_orb = true
				dolphin = true
				item = true
				turtle = true
				salmon = true
				wandering_trader = true
				furnace_minecart = true
				item_frame = true
				horse = true
				phantom = true
				minecart = true
				glow_squid = true
				glow_item_frame = false
				squid = true
				creeper = true
				lightning_bolt = true
				enderman = true
				chicken = true
				trader_llama = true
				donkey = true
				tropical_fish = true
				slime = true
				pillager = true
				iron_golem = true
				zombified_piglin = true
				area_effect_cloud = true
				piglin = true
				blaze = true
				endermite = true
				cat = true
				zombie = true
				sheep = true
				player = true
				pufferfish = true
				potion = true
				wither_skull = true
				villager = true
				wolf = true
				tnt_minecart = true
				zombie_villager = true
				strider = true
				hopper_minecart = true
				painting = true
				cave_spider = true
				cod = true
				witch = true
				snow_golem = true
				spider = true
				wither = true

			[light_sources.settings.entities.dragonloot]
				dragon_trident = true

			[light_sources.settings.entities.charm]
				coral_squid = true

			[light_sources.settings.entities.betternether]
				firefly = true
				skull = true
				naga = true

			[light_sources.settings.entities.guardvillagers]
				guard = true

			[light_sources.settings.entities.creeperspores]
				creeperling = true

			[light_sources.settings.entities.creeperoverhaul]
				swamp_creeper = true
				bamboo_creeper = true
				snowy_creeper = true
				badlands_creeper = true
				desert_creeper = true
				dripstone_creeper = true
				jungle_creeper = true
				cave_creeper = true
				mushroom_creeper = true
				savannah_creeper = true
				hills_creeper = true

			[light_sources.settings.entities.lootr]
				lootr_minecart = true

			[light_sources.settings.entities.gateofbabylon]
				spear = true
				yoyo = true
				boomerang = true

