[graveSettings]
generateGraves = true
retrievalType = "ON_USE"
dropType = "IN_INVENTORY"
dropPlayerHead = false
dropGraveBlock = false
requireGraveItem = false
generateEmptyGraves = false
ignoreSpawnProtection = true
deathInSpawnProtection = "CREATE_GRAVE"
priority = "GRAVE"
unlockableGraves = true
deleteEnchantments = ["minecraft:vanishing_curse", "vanishing_curse"]
soulboundEnchantments = ["yigd:soulbound"]
voidSlots = []
soulboundSlots = [8]
applyBindingCurse = true
trySoft = false
trySoftApproach = "RADIUS"
tryStrict = true
replaceWhenClaimed = true
persistGraves = false
blacklistDimensions = []
graveInVoid = false
ignoreDeathTypes = []
graveSpawnHeight = 2
lastResort = "DROP_ITEMS"
putXpInGrave = false
defaultXpDrop = false
xpDropPercent = 30
tellDeathPos = false
maxGraveBackups = 50

[graveSettings.graveRobbing]
enableRobbing = true
onlyMurderer = false
afterTime = 15
timeType = "MINUTES"
robPriority = "INVENTORY"
tellRobber = true
notifyWhenRobbed = true

[graveSettings.graveDeletion]
canDelete = false
afterTime = 5
timeType = "HOURS"
dropInventory = false

[graveSettings.itemLoss]
enableLoss = true
ignoreSoulboundItems = false
affectStacks = true
usePercentRange = true
lossRangeFrom = 0
lossRangeTo = 15
percentChanceOfLoss = 50

[graveSettings.blockUnderGrave]
generateBlockUnder = true
inOverWorld = "minecraft:cobblestone"
inNether = "minecraft:soul_soil"
inTheEnd = "minecraft:end_stone"
inCustom = "minecraft:dirt"

[graveSettings.graveCompatConfig]
levelzXpInGraves = true
levelzXpDropPercent = 100
claimRuleOverride = "CREATE_GRAVE"
prioritiseTheGraveyardGraves = false
graveyardSearchRadius = 10
keepAllTrinkets = false

[graveSettings.graveRenderSettings]
useRenderFeatures = true
useSpecialBlockRenderer = true
renderGraveSkull = true
renderGraveOwner = true
textShadow = true
adaptRenderer = false
glowingGrave = true
glowMinDistance = 0
glowMaxDistance = 10
[utilitySettings.soulboundEnchant]
enabled = true
isTreasure = true
villagerTrade = true
tableAndLoot = true
[utilitySettings.deathSightEnchant]
enabled = false
isTreasure = true
villagerTrade = true
tableAndLoot = true
[utilitySettings.scrollItem]
scrollType = "DISABLED"
retrieveOnRespawn = true
[utilitySettings.graveKeySettings]
enableKeys = false
alwaysRequire = false
retrieveOnRespawn = true
getFromGui = false
rebindable = false
graveKeySpecification = "PLAYER"
[utilitySettings.graveCompassSettings]
receiveOnDeath = false
tryDeleteOnClaim = true
[commandToggles]
coreCommandName = "yigd"
retrieveGrave = true
robGrave = true
selfView = true
adminView = true
moderateGraves = true
clearGraveBackups = true
whitelist = true
whitelistAdd = true
whitelistRemove = true
whitelistToggle = true
[debugConfig]
clearInventoryOnRespawn = false
createGraveBeforeDeathMessage = false
